import "./globals.css";
import "./styles.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

import { Almarai } from "next/font/google";
const almarai = Almarai({ weight: ['300', '400', '700', '800'], subsets: ["arabic"] });

import { ClerkProvider } from '@clerk/nextjs'
import { BlogProvider } from "./_contexts/BlogContext";
import { CourseProvider } from "./_contexts/CourseContext";
import { FeedbackProvider } from "./_contexts/FeedbackContext";

export const metadata = {
  title: "CHEFANO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider frontendApi={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en" dir="rtl">
        <body className={almarai.className}>
          <Header />
          <BlogProvider>
            <CourseProvider>
              <FeedbackProvider>
                {children}
              </FeedbackProvider>
            </CourseProvider>
          </BlogProvider>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
