import { Almarai } from "next/font/google";
import "./globals.css";
import "./styles.css";
import Footer from "./_components/Footer";

const almarai = Almarai({ weight: ['300', '400', '700', '800'], subsets: ["arabic"] });

export const metadata = {
  title: "CHEFANO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={almarai.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
